name: My APP CI
run-name: Job started by ${{ github.actor }}
on: [ push ]
jobs:
  Maven-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: run tests
        run: mvn clean test
      